const movieConstant = {
  GET_MOVIE_BY_TITLE_SUCCESS: 'GET_MOVIE_BY_TITLE_SUCCESS',
  GET_MOVIE_BY_TITLE_FAILED: 'GET_MOVIE_BY_TITLE_FAILED',
  GET_MOVIE_BY_TITLE_LOADING: ' GET_MOVIE_BY_TITLE_LOADING',
  GET_MOVIE_DETAIL_SUCCESS: 'GET_MOVIE_DETAIL_SUCCESS',
  GET_MOVIE_DETAIL_FAILED: 'GET_MOVIE_DETAIL_FAILED',
  GET_MOVIE_DETAIL_LOADING: ' GET_MOVIE_DETAIL_LOADING',
};

export default movieConstant;
